global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'micronaut'
    metrics_path: '/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.0.45:8080', '192.168.0.45:8081', '192.168.0.45:8082']
