global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'spring_micrometer'
    metrics_path: '/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.0.45:8050', '192.168.0.45:8070', '192.168.0.45:8060', '192.168.0.45:8080']
